Oak
hugpoint-tech/phab-migration-tools pull request #7
Opened 2024-03-12 01:28 UTC by Xeonid

2024-03-12 05:05 UTC, ngortheone requested changes

2024-03-12 05:05 UTC, ngortheone commented on bugz/DownloadBugzillaUsers.go
> +	for id, _ := range idUserMap {
Rework this loop. 
We no longer need to fetch users from API. Just save each user to json file. I.e.
```
for id, user := range idUserMap {
// save user to file
}
```

2024-03-24 01:12 UTC, Xeonid commented on bugz/getToken.go
> +package usersJson
ok

2024-03-24 01:12 UTC, Xeonid commented on bugz/DownloadBugzillaUsers.go
> +	err := os.Mkdir("usersJson", os.ModePerm)
ok

2024-03-24 01:13 UTC, Xeonid commented on bugz/DownloadBugzillaUsers.go
> +	for id, _ := range idUserMap {
ok

2024-03-25 04:33 UTC, closed without merging