Update client.go
hugpoint-tech/phab-migration-tools pull request #8
Opened 2024-03-23 10:46 UTC by Xeonid

2024-03-24 14:43 UTC, ngortheone requested changes

2024-03-24 14:43 UTC, ngortheone commented on bugz/client.go
> +	Token string
Why do you need to make token public?

2024-03-24 14:43 UTC, ngortheone commented on bugz/client.go
> +func (bc *BugzClient) GetToken() string {
Why do you need this method?

2024-03-24 14:43 UTC, ngortheone commented on bugz/client.go
> +func (bc *BugzClient) DownloadBugs() ([]Bug, error) {
This method does not download **all** bugs.

2024-03-25 16:32 UTC, ngortheone requested changes

2024-03-26 08:57 UTC, Xeonid commented on bugz/client.go
> +func (bc *BugzClient) GetToken() string {
ok

2024-03-26 08:58 UTC, Xeonid commented on main.go
> +	/*func getBugsFromBugzilla(pullConcurrencyLevel int, chanBug chan bugz.Bug) {
ok

2024-03-26 08:58 UTC, Xeonid commented on main.go
> +	func showBugs() {
ok

2024-03-26 08:58 UTC, Xeonid commented on main.go
> +	func listBugs() {
ok

2024-03-26 08:58 UTC, Xeonid commented on bugz/getToken.go
> +func GetToken() (string, error) {
ok

2024-03-26 08:58 UTC, Xeonid commented on bugz/getIDS.go
> +func getIDS() (map[int]User, error) {
ok

2024-03-26 08:58 UTC, Xeonid commented on bugz/client.go
> +func (bc *BugzClient) GetToken() (string, error) {
ok

2024-03-26 09:04 UTC, Xeonid commented on bugz/client.go
> +	Token string
ok

2024-03-27 10:45 UTC, Xeonid commented on bugz/getUsers.go
> +func DownloadBugzillaUsers() {
ok

2024-03-27 10:45 UTC, Xeonid commented on bugz/bugs.go
> +func DownloadBugzillaBugs() error {
ok

2024-03-27 10:45 UTC, Xeonid commented on bugz/client.go
> +	return DownloadBugzillaBugs()
ok

2024-04-02 00:29 UTC, Xeonid commented on bugz/client.go
> +func (bc *BugzClient) DownloadBugs() ([]Bug, error) {
ok

2024-04-02 03:17 UTC, ngortheone requested changes

2024-04-02 03:17 UTC, ngortheone commented on bugz/bugs.go
> +func DownloadBugzillaBugs() error {
why does this function exist?

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +	apiURL := "https://bugs.freebsd.org/bugzilla/rest/bug"
reuse `bc.URL here`

2024-04-02 03:17 UTC, ngortheone commented on bugz/getIDS.go
> +		fmt.Printf("Error reading directory: %v\n", err)
Normally you either return the error to the caller or handle it on the spot.
Printing the error is "handing it". Here you are trying to do a bit of both.

Suggest to replace this with 
```
if err != nil {
    return nil, fmt.Errorf("Error reading directory: %w", err)
}
```

And do the printing in the calling function

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +		return nil
This is wrong. 

If `err !=nil` means we have a problem. But returning `nil` to the caller you say "no problems happened".

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +		fmt.Printf("Error creating 'users' folder: %v\n", err)
Returning nil to the caller you say "no problems happened".

replace this with
```
return fmt.Errorf("Error creating 'users' folder: %w", err)
```

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +		fmt.Printf("Error reading directory: %v\n", err)
Same here. See my other comments about return values

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +				return fmt.Errorf("Error writing to file %s: %v\n", filename, err)
No need to add explicit newline '\n' in Errorf

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +			return fmt.Errorf("Error decoding JSON: %v\n", err)
No need to add explicit newline '\n' in Errorf

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +			return fmt.Errorf("Error reading response body from %s: %v\n", fullURL, err)
No need to add explicit newline '\n' in Errorf

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +			return fmt.Errorf("Error making GET request to %s: %v\n", fullURL, err)
No need to add explicit newline '\n' in Errorf

2024-04-02 03:17 UTC, ngortheone commented on bugz/client.go
> +		return fmt.Errorf("Error creating 'users' folder: %v\n", err)
No need to add explicit newline '\n' in Errorf

2024-04-04 04:43 UTC, ngortheone requested changes

2024-04-04 04:43 UTC, ngortheone commented on bugz/client.go
> +	//login := os.Getenv("BUGZILLA_LOGIN") //Retrieve env var values and check if they are empty
do not commit commented out code

2024-04-04 21:57 UTC, ngortheone requested changes

2024-04-04 21:57 UTC, ngortheone commented on bugz/client.go
> +		response, err := http.Get(fullURL)
why not `bc.http.Get(...` ? Use it since we have created it in the struct.

2024-04-04 21:57 UTC, ngortheone commented on bugz/client.go
> +		params.Set("api_key", "val")
I think here you are supposed to use `bc.token`

2024-04-04 21:57 UTC, ngortheone commented on bugz/client.go
> +
In this function you are supposed to login and use `BugzLoginResponse` to get a token and save token to the struct,

2024-04-04 21:57 UTC, ngortheone commented on bugz/client.go
> -	response, err := bugz.http.Get(bugz.url + "/login?" + formData.Encode())
You have deleted the code that does the login, and I don't see an alternative.
How does BugzlillaClient authenticate?

2024-04-04 22:01 UTC, ngortheone commented on main.go
> +		fmt.Println("use help")
sidenote: you can say "invalid command" and call `printHelp()` here.

2024-04-05 03:22 UTC, ngortheone requested changes

2024-04-05 03:22 UTC, ngortheone commented on bugz/client.go
> +	response, _ := bc.http.Get(bc.URL + "/login?" + formData.Encode())
do not ignore the error here

2024-04-05 04:26 UTC, ngortheone approved these changes

2024-04-05 04:27 UTC, merged